class DailyProfileResource < JSONAPI::Resource
  attributes :eaten_at
  attributes :energy
  attributes :carbohydrates
  attributes :fat
  attributes :protein
  attributes :fiber
  attributes :water
  attributes :alcohol
  attributes :ash
  attributes :sucrose
  attributes :whole_grains_total
  attributes :sugar_types
  attributes :epa
  attributes :dpa
  attributes :dha
  attributes :retinol
  attributes :vitamin_a
  attributes :b_carotene
  attributes :vitamin_d
  attributes :vitamin_e
  attributes :vitamin_k
  attributes :riboflavin
  attributes :vitamin_c
  attributes :niacin
  attributes :niacin_equivalents
  attributes :vitamin_b6
  attributes :folate
  attributes :phosphorus
  attributes :iron
  attributes :calcium
  attributes :potassium
  attributes :magnesium
  attributes :sodium
  attributes :selenium
  attributes :zinc
  attributes :waste

  attributes :energy_rdi_precentage
  attributes :carbohydrates_rdi_precentage
  attributes :fat_rdi_precentage
  attributes :protein_rdi_precentage
  attributes :fiber_rdi_precentage
  attributes :water_rdi_precentage
  attributes :alcohol_rdi_precentage
  attributes :ash_rdi_precentage
  attributes :sucrose_rdi_precentage
  attributes :whole_grains_total
  attributes :sugar_types_rdi_precentage
  attributes :epa_rdi_precentage
  attributes :dpa_rdi_precentage
  attributes :dha_rdi_precentage
  attributes :retinol_rdi_precentage
  attributes :vitamin_a_rdi_precentage
  attributes :b_carotene_rdi_precentage
  attributes :vitamin_d_rdi_precentage
  attributes :vitamin_e_rdi_precentage
  attributes :vitamin_k_rdi_precentage
  attributes :riboflavin_rdi_precentage
  attributes :vitamin_c_rdi_precentage
  attributes :niacin_rdi_precentage
  attributes :niacin_equivalents_rdi_precentage
  attributes :vitamin_b6_rdi_precentage
  attributes :folate_rdi_precentage
  attributes :phosphorus_rdi_precentage
  attributes :iron_rdi_precentage
  attributes :calcium_rdi_precentage
  attributes :potassium_rdi_precentage
  attributes :magnesium_rdi_precentage
  attributes :sodium_rdi_precentage
  attributes :selenium_rdi_precentage
  attributes :zinc_rdi_precentage
  attributes :waste_rdi_precentage # probably don't need this, but we will see.
end
